module;

#include <vulkan/vulkan.hpp>

module VulkanSimplifiers.Common.PipelineStageFlags.Internal;

VkPipelineStageFlags TranslateStageFlags(PipelineStageFlags stageFlags)
{
	VkPipelineStageFlags ret = 0;

	if ((stageFlags & PIPELINE_STAGE_TOP_OF_PIPE) == PIPELINE_STAGE_TOP_OF_PIPE)
		ret |= VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT;

	if ((stageFlags & PIPELINE_STAGE_DRAW_INDIRECT) == PIPELINE_STAGE_DRAW_INDIRECT)
		ret |= VK_PIPELINE_STAGE_DRAW_INDIRECT_BIT;

	if ((stageFlags & PIPELINE_STAGE_VERTEX_INPUT) == PIPELINE_STAGE_VERTEX_INPUT)
		ret |= VK_PIPELINE_STAGE_VERTEX_INPUT_BIT;

	if ((stageFlags & PIPELINE_STAGE_VERTEX_SHADER) == PIPELINE_STAGE_VERTEX_SHADER)
		ret |= VK_PIPELINE_STAGE_VERTEX_SHADER_BIT;

	if ((stageFlags & PIPELINE_STAGE_TESSELATION_CONTROL_SHADER) == PIPELINE_STAGE_TESSELATION_CONTROL_SHADER)
		ret |= VK_PIPELINE_STAGE_TESSELLATION_CONTROL_SHADER_BIT;

	if ((stageFlags & PIPELINE_STAGE_TESSELATION_EVALUATION_SHADER) == PIPELINE_STAGE_TESSELATION_EVALUATION_SHADER)
		ret |= VK_PIPELINE_STAGE_TESSELLATION_EVALUATION_SHADER_BIT;

	if ((stageFlags & PIPELINE_STAGE_GEOMETRY_SHADER) == PIPELINE_STAGE_GEOMETRY_SHADER)
		ret |= VK_PIPELINE_STAGE_GEOMETRY_SHADER_BIT;

	if ((stageFlags & PIPELINE_STAGE_FRAGMENT_SHADER) == PIPELINE_STAGE_FRAGMENT_SHADER)
		ret |= VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT;

	if ((stageFlags & PIPELINE_STAGE_EARLY_FRAGMENT_TEST) == PIPELINE_STAGE_EARLY_FRAGMENT_TEST)
		ret |= VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT;

	if ((stageFlags & PIPELINE_STAGE_LATE_FRAGMENT_TEST) == PIPELINE_STAGE_LATE_FRAGMENT_TEST)
		ret |= VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT;

	if ((stageFlags & PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT) == PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT)
		ret |= VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;

	if ((stageFlags & PIPELINE_STAGE_COMPUTE_SHADER) == PIPELINE_STAGE_COMPUTE_SHADER)
		ret |= VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT;

	if ((stageFlags & PIPELINE_STAGE_TRANSFER) == PIPELINE_STAGE_TRANSFER)
		ret |= VK_PIPELINE_STAGE_TRANSFER_BIT;

	if ((stageFlags & PIPELINE_STAGE_BOTTOM_OF_PIPE) == PIPELINE_STAGE_BOTTOM_OF_PIPE)
		ret |= VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT;

	if ((stageFlags & PIPELINE_STAGE_HOST) == PIPELINE_STAGE_HOST)
		ret |= VK_PIPELINE_STAGE_HOST_BIT;

	if ((stageFlags & PIPELINE_STAGE_ALL_GRAPHICS) == PIPELINE_STAGE_ALL_GRAPHICS)
		ret |= VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT;

	if ((stageFlags & PIPELINE_STAGE_ALL_COMMANDS) == PIPELINE_STAGE_ALL_COMMANDS)
		ret |= VK_PIPELINE_STAGE_ALL_COMMANDS_BIT;

	return ret;
}