module;

#include <vulkan/vulkan.hpp>

module VulkanSimplifiers.Common.ImageUsageFlags.Internal;

VkImageUsageFlags TranslateImageUsage(ImageUsageFlags usageFlags)
{
	VkImageUsageFlags ret = 0;

	if ((usageFlags & IMAGE_USAGE_TRANSFER_SRC) == IMAGE_USAGE_TRANSFER_SRC)
		ret |= VK_IMAGE_USAGE_TRANSFER_SRC_BIT;

	if ((usageFlags & IMAGE_USAGE_TRANSFER_DST) == IMAGE_USAGE_TRANSFER_DST)
		ret |= VK_IMAGE_USAGE_TRANSFER_DST_BIT;

	if ((usageFlags & IMAGE_USAGE_SAMPLED) == IMAGE_USAGE_SAMPLED)
		ret |= VK_IMAGE_USAGE_SAMPLED_BIT;

	if ((usageFlags & IMAGE_USAGE_STORAGE) == IMAGE_USAGE_STORAGE)
		ret |= VK_IMAGE_USAGE_STORAGE_BIT;

	if ((usageFlags & IMAGE_USAGE_COLOR_ATTACHMENT) == IMAGE_USAGE_COLOR_ATTACHMENT)
		ret |= VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT;

	if ((usageFlags & IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT) == IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT)
		ret |= VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT;

	if ((usageFlags & IMAGE_USAGE_TRANSIENT_ATTACHMENT) == IMAGE_USAGE_TRANSIENT_ATTACHMENT)
		ret |= VK_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT;

	if ((usageFlags & IMAGE_USAGE_INPUT_ATTACHMENT) == IMAGE_USAGE_INPUT_ATTACHMENT)
		ret |= VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT;

	return ret;
}