export module VulkanSimplifiers.Common.DeviceFeatureFlags;

import std;

export typedef std::uint64_t VulkanDeviceFeatureFlags;

export enum Vulkan10DeviceFeaturesFlagBits : VulkanDeviceFeatureFlags
{
	VULKAN10_DEVICE_FEATURE_FULL_DRAW_INDEX_UINT32 = 0x1,
	VULKAN10_DEVICE_FEATURE_INDEPENDENT_BLEND = 0x2,
	VULKAN10_DEVICE_FEATURE_FILL_MODE_NONSOLID = 0x4,
	VULKAN10_DEVICE_FEATURE_SAMPLER_ANISOTROPY = 0x8,
	VULKAN10_DEVICE_FEATURE_TEXTURE_COMPRESSION_ETC2 = 0x10,
	VULKAN10_DEVICE_FEATURE_TEXTURE_COMPRESSION_ASTC_LDR = 0x20,
	VULKAN10_DEVICE_FEATURE_TEXTURE_COMPRESSION_BC = 0x40,
	VULKAN10_DEVICE_FEATURE_SHADER_FLOAT64 = 0x80,
	VULKAN10_DEVICE_FEATURE_SHADER_INT64 = 0x100,
	VULKAN10_DEVICE_FEATURE_SHADER_INT16 = 0x200,
	VULKAN10_DEVICE_FEATURE_SHADER_RESOURCE_RESIDENCY = 0x400,
	VULKAN10_DEVICE_FEATURE_SHADER_RESOURCE_MINIMUM_LOD = 0x800,
};